# Generated by Django 4.2.11 on 2024-04-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Start_date", models.DateField()),
                ("Start_time", models.TimeField()),
                ("Program", models.CharField(max_length=20)),
                ("Clasification", models.CharField(max_length=100)),
                ("Digital_EPG_synopsis", models.CharField(max_length=100)),
                ("Episode_title", models.CharField(max_length=100)),
                ("Major_program_genre", models.CharField(max_length=100)),
                ("Sub_genre", models.CharField(max_length=100)),
                ("Year_of_production", models.IntegerField()),
                ("Actors", models.CharField(max_length=100)),
                ("Nominal_length", models.IntegerField()),
                ("Closed_captions", models.BooleanField(default=True)),
                ("Premiere_episode", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
