# Generated by Django 4.2.11 on 2024-04-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EPG_creation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="Program",
            new_name="Program_title",
        ),
    ]
