# Generated by Django 4.2.11 on 2024-05-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EPG_creation", "0002_rename_program_listing_program_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField()),
                ("Time", models.TimeField()),
                ("Name_of_program", models.CharField(max_length=100)),
                ("Description", models.TextField()),
            ],
        ),
    ]
